version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-api/public:/var/www/html
    depends_on:
      - app

  app:
      build: ./laravel-api
      container_name: app_container
      working_dir: /var/www
      volumes:
        - ./laravel-api:/var/www
      depends_on:
        - db

  db:
    image: mysql:5.7
    container_name: db_container
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: node:18
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./vue-frontend:/app
    command: ["npm", "run", "serve"]

volumes:
  mysql_data:
